fun main() {
    try {
        10 / 2
    } catch (e: Exception) {
    }
}